---
title: "Pl-CDI-III Norming Study"
subtitle: "Item-level Analysis"
author: "Grzegorz Krajewski"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
#    toc: true
#    toc_float: true
#    code_folding: hide
---

```{r setup, include=FALSE}
# Packages:
library(tidyverse)
library(Multilada)
library(ggpubr) # for many plots

# knitr chunk defaults:
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

# Latest website download:
export_date <- list.files(pattern ="_[0-9]{8}\\.csv") %>%
  str_extract("[0-9]{8}") %>% sort() %>% last()

# Data import:
read_csv(paste0("submissions_", export_date, ".csv")) -> submissions
read_csv(paste0("responses_", export_date, ".csv")) -> responses
```


```{r construction_types}
read_csv2("items.csv") -> items
items %>%
  mutate(q_main = gsub("[^[:alpha:]]", "", definition)) -> items # to avoid „ vs " etc. mismatches

read_csv("structures_all.csv") %>%
  select(! starts_with("typ")) %>% distinct() %>% # keep English & avoid complex-relative vs względne mismatch
  mutate(q2 = str_replace_na(q2, "")) %>%
  mutate(q_main = paste(q1, q2)) %>%
  mutate(q_main = gsub("[^[:alpha:]]", "", q_main)) %>% # to avoid „ vs " etc. mismatches
  right_join(items) %>%
  select(! starts_with("q") & ! "alternatywa") -> items
```


```{r itemise}
# Lexicon:

cdi_itemise_oneCheckboxGroup(responses, "word", items) -> lex_responses
# Add IDs with no items checked, not included in the above output:
submissions %>% filter(! id %in% lex_responses$id) %>% select(id, end_date) %>%
  group_by(id, end_date) %>% group_modify(~ {
    items %>% filter(type == "word") %>% group_by(category) %>% mutate(item_id = row_number()) %>%
      add_column(response = 0, id = .x$id, end_date = .x$end_date)
  }) %>% bind_rows(lex_responses) -> lex_responses


# Alternatives:

cdi_itemise_checkboxAlt(responses, "alternatives", items) %>%
  rename(response = "answer2") %>%
  select(-answer1) -> alt_responses
# One submission (MZ4ff15UPqUXBdp5Fm6ek) without any alternatives saved... (check similar case in the pilot).
# Add MZ4ff15UPqUXBdp5Fm6ek, not included in the above output:
submissions %>% filter(! id %in% alt_responses$id) %>% select(id, end_date) %>%
  group_by(id, end_date) %>% group_modify(~ {
    items %>% filter(type == "alternatives") %>% group_by(category) %>% mutate(item_id = row_number()) %>%
      add_column(response = 0, id = .x$id, end_date = .x$end_date)
  }) %>% bind_rows(alt_responses) -> alt_responses


# Direct questions:

cdi_itemise_radio(responses, "yesNo", items) %>%
  rename(response = "answer") %>%
  mutate(response = if_else(response == 1, 1, 0)) -> direct_responses

```


## Grammar items difficulties by age

We bind together complexity alternatives and direct questions
and we calculate difficulties by age.

```{r diff_grammar_age}
bind_rows(alt_responses, direct_responses) %>%
  right_join(submissions[submissions$age_range,]) -> gram_responses
(
gram_responses %>%
  group_by(definition, construction, age) %>% summarise(difficulty = mean(response)) -> diff_gram
)
submissions %>% filter(age_range) %>% group_by(age) %>% summarise(N = n())
```


Below are barplots of difficulty by age with binomial smoothing.

```{r diff_grammar_age_plot}
gram_responses %>% group_by(definition) %>%
      group_map(~ {
        ggplot(.x) +
          aes(age, response) +
          stat_summary(fun = "mean", geom = "bar") +
          geom_smooth(method = "glm", method.args=list(family="binomial")) +
          labs(x = "Age (months)", y = "Checked", title = .y) +
          ylim(0, 1)
      }) -> gram_diff_plots
ggarrange(plotlist = gram_diff_plots, nrow = 4, ncol = 6)
```


```{r diff_grammar_age_stats}
gram_responses %>% group_by(definition) %>%
        group_modify(~ {
                glm(response ~ age, family = binomial, .x) -> item_model
                summary(item_model)$coefficients["age", ] -> age_estimation
                cbind(data.frame(age_deviance = item_model$deviance, age_aic = item_model$aic),
                      age_coefficient = age_estimation[1], age_pvalue = age_estimation[4])
        }) -> gram_item_age
```


```{r diff_grammar_age_predicted}
gram_responses %>% group_by(definition) %>%
        group_modify(~ {
                glm(response ~ age, family = binomial, .x) -> item_model
                data.frame(t(predict(item_model,
                                     data.frame(age=min(.x$age) : max(.x$age)),
                                     type = "response"))) -> pred
                colnames(pred) <- paste("m", min(.x$age) : max(.x$age), sep = "_")
                pred
        }) -> gram_item_age_predicted
```


